name: Update whatsmeow

on:
  repository_dispatch:
    types: [update-whatsmeow]
  workflow_dispatch:
  
concurrency:
  group: check-and-update-whatsmeow

jobs:
  update_whatsmeow:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Update whatsmeow
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          bash update.sh
          git add .
          git commit -m "Update"
          git push
 